import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import styled from "styled-components";

import { MyComp, MyComp2 } from "@/components";

export default function Home() {
  useEffect(() => {
    (async () => {
      const res = await axios.get("/api/hello");
      console.log(res.data.data);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>홈페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>gdgd</div>
    </>
  );
}

const Div = styled.div`
  width: 100vw;
  height: 100vh;

  .container {
    width: 300px;
    height: 100px;
    background-color: coral;
    display: flex;
    gap: 10px;
    overflow: auto;
    padding: 10px;
  }
  .item {
    flex-shrink: 0;
    /* flex: 0 0 auto; */
    width: 200px;
    height: 60px;
    background-color: lightblue;
  }
`;
